# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lampada_pb2 as lampada__pb2


class LampadaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ligarLampada = channel.unary_unary(
                '/Lampada/ligarLampada',
                request_serializer=lampada__pb2.LampadaStatus.SerializeToString,
                response_deserializer=lampada__pb2.LampadaStatus.FromString,
                )
        self.desligarLampada = channel.unary_unary(
                '/Lampada/desligarLampada',
                request_serializer=lampada__pb2.LampadaStatus.SerializeToString,
                response_deserializer=lampada__pb2.LampadaStatus.FromString,
                )


class LampadaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ligarLampada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def desligarLampada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LampadaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ligarLampada': grpc.unary_unary_rpc_method_handler(
                    servicer.ligarLampada,
                    request_deserializer=lampada__pb2.LampadaStatus.FromString,
                    response_serializer=lampada__pb2.LampadaStatus.SerializeToString,
            ),
            'desligarLampada': grpc.unary_unary_rpc_method_handler(
                    servicer.desligarLampada,
                    request_deserializer=lampada__pb2.LampadaStatus.FromString,
                    response_serializer=lampada__pb2.LampadaStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Lampada', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Lampada(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ligarLampada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Lampada/ligarLampada',
            lampada__pb2.LampadaStatus.SerializeToString,
            lampada__pb2.LampadaStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def desligarLampada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Lampada/desligarLampada',
            lampada__pb2.LampadaStatus.SerializeToString,
            lampada__pb2.LampadaStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
