# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import exaustor_pb2 as exaustor__pb2


class ExaustorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ligarExaustor = channel.unary_unary(
                '/Exaustor/ligarExaustor',
                request_serializer=exaustor__pb2.StatusExaustor.SerializeToString,
                response_deserializer=exaustor__pb2.StatusExaustor.FromString,
                )
        self.desligarExaustor = channel.unary_unary(
                '/Exaustor/desligarExaustor',
                request_serializer=exaustor__pb2.StatusExaustor.SerializeToString,
                response_deserializer=exaustor__pb2.StatusExaustor.FromString,
                )


class ExaustorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ligarExaustor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def desligarExaustor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExaustorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ligarExaustor': grpc.unary_unary_rpc_method_handler(
                    servicer.ligarExaustor,
                    request_deserializer=exaustor__pb2.StatusExaustor.FromString,
                    response_serializer=exaustor__pb2.StatusExaustor.SerializeToString,
            ),
            'desligarExaustor': grpc.unary_unary_rpc_method_handler(
                    servicer.desligarExaustor,
                    request_deserializer=exaustor__pb2.StatusExaustor.FromString,
                    response_serializer=exaustor__pb2.StatusExaustor.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Exaustor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Exaustor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ligarExaustor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Exaustor/ligarExaustor',
            exaustor__pb2.StatusExaustor.SerializeToString,
            exaustor__pb2.StatusExaustor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def desligarExaustor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Exaustor/desligarExaustor',
            exaustor__pb2.StatusExaustor.SerializeToString,
            exaustor__pb2.StatusExaustor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
