# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ar.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08\x61r.proto\"$\n\rArTemperatura\x12\x13\n\x0btemperatura\x18\x01 \x01(\x02\x32\x61\n\x02\x41r\x12+\n\x07ligarAr\x12\x0e.ArTemperatura\x1a\x0e.ArTemperatura\"\x00\x12.\n\ndesligarAr\x12\x0e.ArTemperatura\x1a\x0e.ArTemperatura\"\x00\x62\x06proto3'
)




_ARTEMPERATURA = _descriptor.Descriptor(
  name='ArTemperatura',
  full_name='ArTemperatura',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperatura', full_name='ArTemperatura.temperatura', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=48,
)

DESCRIPTOR.message_types_by_name['ArTemperatura'] = _ARTEMPERATURA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArTemperatura = _reflection.GeneratedProtocolMessageType('ArTemperatura', (_message.Message,), {
  'DESCRIPTOR' : _ARTEMPERATURA,
  '__module__' : 'ar_pb2'
  # @@protoc_insertion_point(class_scope:ArTemperatura)
  })
_sym_db.RegisterMessage(ArTemperatura)



_AR = _descriptor.ServiceDescriptor(
  name='Ar',
  full_name='Ar',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=50,
  serialized_end=147,
  methods=[
  _descriptor.MethodDescriptor(
    name='ligarAr',
    full_name='Ar.ligarAr',
    index=0,
    containing_service=None,
    input_type=_ARTEMPERATURA,
    output_type=_ARTEMPERATURA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='desligarAr',
    full_name='Ar.desligarAr',
    index=1,
    containing_service=None,
    input_type=_ARTEMPERATURA,
    output_type=_ARTEMPERATURA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AR)

DESCRIPTOR.services_by_name['Ar'] = _AR

# @@protoc_insertion_point(module_scope)
